<a href="https://colab.research.google.com/github/YOUGALAKSHMI/Data-Analysis-Visuvalization/blob/main/day_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:

fruits=pd.Series(['apple','banana','orange'],
index=['a','b','c'])

In [ ]:
l=[1,2,3]
l*2

[1, 2, 3, 1, 2, 3]

In [ ]:
s=pd.Series(l)
s*2

0    2
1    4
2    6
dtype: int64

In [ ]:
d={"1":["mech","aero"],"2":["cse","it"],"3":["fd","bt"]}
d1=pd.DataFrame(d)
d1

      1    2   3
0  mech  cse  fd
1  aero   it  bt

In [ ]:
count=pd.Series(['1','2','3'],
index=['a','b','c'])

In [ ]:
fru=pd.DataFrame({"fruits name":fruits,"no of fruits":count})

In [ ]:
fru['fruits name']

a     apple
b    banana
c    orange
Name: fruits name, dtype: object

In [ ]:
print(type(fru['fruits name']))

<class 'pandas.core.series.Series'>

In [ ]:
fru

  fruits name no of fruits
a       apple            1
b      banana            2
c      orange            3

In [ ]:
fru.index

Index(['a', 'b', 'c'], dtype='object')

In [ ]:
fru.reindex(['a','c','b'])

  fruits name no of fruits
a       apple            1
c      orange            3
b      banana            2

In [ ]:
f=fru.sort_index()
f

  fruits name no of fruits
a       apple            1
b      banana            2
c      orange            3

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/diabetes.csv")

In [ ]:
df.shape

(768, 9)

In [ ]:
df.isnull()

     pregnant  glucose     bp   skin  insulin    bmi  pedigree    age  label
0       False    False  False  False    False  False     False  False  False
1       False    False  False  False    False  False     False  False  False
2       False    False  False  False    False  False     False  False  False
3       False    False  False  False    False  False     False  False  False
4       False    False  False  False    False  False     False  False  False
..        ...      ...    ...    ...      ...    ...       ...    ...    ...
763     False    False  False  False    False  False     False  False  False
764     False    False  False  False    False  False     False  False  False
765     False    False  False  False    False  False     False  False  False
766     False    False  False  False    False  False     False  False  False
767     False    False  False  False    False  False     False  False  False

[768 rows x 9 columns]

In [ ]:
df.dropna(0,inplace=True)

<ipython-input-20-d541b3bc4964>:1: FutureWarning: In a future version of pandas all arguments of DataFrame.dropna will be keyword-only.
  df.dropna(0,inplace=True)

In [ ]:
df.head()

   pregnant  glucose  bp  skin  insulin   bmi  pedigree  age  label
0         6      148  72    35        0  33.6     0.627   50      1
1         1       85  66    29        0  26.6     0.351   31      0
2         8      183  64     0        0  23.3     0.672   32      1
3         1       89  66    23       94  28.1     0.167   21      0
4         0      137  40    35      168  43.1     2.288   33      1

In [ ]:
df.tail(7)

     pregnant  glucose  bp  skin  insulin   bmi  pedigree  age  label
761         9      170  74    31        0  44.0     0.403   43      1
762         9       89  62     0        0  22.5     0.142   33      0
763        10      101  76    48      180  32.9     0.171   63      0
764         2      122  70    27        0  36.8     0.340   27      0
765         5      121  72    23      112  26.2     0.245   30      0
766         1      126  60     0        0  30.1     0.349   47      1
767         1       93  70    31        0  30.4     0.315   23      0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pregnant  768 non-null    int64
 1   glucose   768 non-null    int64
 2   bp        768 non-null    int64
 3   skin      768 non-null    int64
 4   insulin   768 non-null    int64
 5   bmi       768 non-null    float64
 6   pedigree  768 non-null    float64
 7   age       768 non-null    int64
 8   label     768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [ ]:
df.describe()

,pregnant,glucose,bp,skin,insulin,bmi,pedigree,age,label
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [ ]:
df1=df.append(df)

<ipython-input-31-e662683af4d3>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1=df.append(df)

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1536 entries, 0 to 767
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pregnant  1536 non-null   int64
 1   glucose   1536 non-null   int64
 2   bp        1536 non-null   int64
 3   skin      1536 non-null   int64
 4   insulin   1536 non-null   int64
 5   bmi       1536 non-null   float64
 6   pedigree  1536 non-null   float64
 7   age       1536 non-null   int64
 8   label     1536 non-null   int64
dtypes: float64(2), int64(7)
memory usage: 120.0 KB

In [ ]:
df.drop_duplicates(inplace=True,keep='first')  #first last false

In [ ]:
df.drop_duplicates(subset=['age'])

     pregnant  glucose   bp  skin  insulin   bmi  pedigree  age  label
0           6      148   72    35        0  33.6     0.627   50      1
1           1       85   66    29        0  26.6     0.351   31      0
2           8      183   64     0        0  23.3     0.672   32      1
3           1       89   66    23       94  28.1     0.167   21      0
4           0      137   40    35      168  43.1     2.288   33      1
5           5      116   74     0        0  25.6     0.201   30      0
6           3       78   50    32       88  31.0     0.248   26      1
7          10      115    0     0        0  35.3     0.134   29      0
8           2      197   70    45      543  30.5     0.158   53      1
9           8      125   96     0        0   0.0     0.232   54      1
11         10      168   74     0        0  38.0     0.537   34      1
12         10      139   80     0        0  27.1     1.441   57      0
13          1      189   60    23      846  30.1     0.398   59      1
14          5      166   72    19      175  25.8     0.587   51      1
20          3      126   88    41      235  39.3     0.704   27      0
22          7      196   90     0        0  39.8     0.451   41      1
26          7      147   76     0        0  39.4     0.257   43      1
27          1       97   66    15      140  23.2     0.487   22      0
29          5      117   92     0        0  34.1     0.337   38      0
30          5      109   75    26        0  36.0     0.546   60      0
31          3      158   76    36      245  31.6     0.851   28      1
34         10      122   78    31        0  27.6     0.512   45      0
36         11      138   76     0        0  33.2     0.420   35      0
37          9      102   76    37        0  32.9     0.665   46      1
39          4      111   72    47      207  37.1     1.390   56      1
41          7      133   84     0        0  40.2     0.696   37      0
42          7      106   92    18        0  22.7     0.235   48      0
44          7      159   64     0        0  27.4     0.294   40      0
45          0      180   66    39        0  42.0     1.893   25      1
49          7      105    0     0        0   0.0     0.305   24      0
53          8      176   90    34      300  33.7     0.467   58      1
54          7      150   66    42      342  34.7     0.718   42      0
58          0      146   82     0        0  40.5     1.781   44      0
61          8      133   72     0        0  32.9     0.270   39      1
62          5       44   62     0        0  25.0     0.587   36      0
73          4      129   86    20      270  35.1     0.231   23      0
115         4      146   92     0        0  31.2     0.539   61      1
123         5      132   80     0        0  26.8     0.186   69      0
129         0      105   84     0        0  27.9     0.741   62      1
140         3      128   78     0        0  21.1     0.268   55      0
148         5      147   78     0        0  33.7     0.218   65      0
159        17      163   72    41      114  40.9     0.817   47      1
207         5      162  104     0        0  37.7     0.151   52      1
221         2      158   90     0        0  31.6     0.805   66      1
245         9      184   85    15        0  30.0     1.213   49      1
263         3      142   80    15        0  32.4     0.200   63      0
363         4      146   78     0        0  38.5     0.520   67      1
453         2      119    0     0        0  19.6     0.832   72      0
459         9      134   74    33       60  25.9     0.460   81      0
509         8      120   78     0        0  25.0     0.409   64      0
666         4      145   82    18        0  32.5     0.235   70      1
674         8       91   82     0        0  35.6     0.587   68      0

In [ ]:
df1=pd.DataFrame(data)

In [ ]:
df1.shape

(19, 9)

In [ ]:
df1.describe()

,Area,Perimeter,MajorAxisLength,MinorAxisLength,AspectRation,Eccentricity,ConvexArea,EquivDiameter,Extent
count,19.000000,19.000000,19.000000,10.000000,10.000000,10.000000,19.000000,19.000000,19.000000
mean,30512.473684,637.061947,211.825565,182.935268,1.157632,0.500343,30877.368421,197.084557,0.774774
std,855.330629,11.934457,4.340437,4.596936,0.033368,0.044262,843.453958,2.788287,0.009967
min,28395.000000,610.291000,200.524796,173.888747,1.097356,0.411785,28715.000000,190.141097,0.761046
25%,30209.500000,633.430500,210.804077,182.570992,1.135055,0.473031,30662.000000,196.122103,0.767216
50%,30834.000000,638.558000,212.826130,184.057998,1.158477,0.504781,31120.000000,198.139012,0.773098
75%,31158.000000,640.935000,214.104319,186.140285,1.176361,0.526603,31483.000000,199.177302,0.781997
max,31272.000000,670.033000,217.227813,187.535939,1.209713,0.562727,31593.000000,199.541342,0.798759

In [ ]:
data=pd.read_csv("/content/data.csv")
df=pd.read_csv("/content/data.csv")

In [ ]:
data.shape

(19, 9)

In [ ]:
data.describe()

,Area,Perimeter,MajorAxisLength,MinorAxisLength,AspectRation,Eccentricity,ConvexArea,EquivDiameter,Extent
count,19.000000,19.000000,19.000000,10.000000,10.000000,10.000000,19.000000,19.000000,19.000000
mean,30512.473684,637.061947,211.825565,182.935268,1.157632,0.500343,30877.368421,197.084557,0.774774
std,855.330629,11.934457,4.340437,4.596936,0.033368,0.044262,843.453958,2.788287,0.009967
min,28395.000000,610.291000,200.524796,173.888747,1.097356,0.411785,28715.000000,190.141097,0.761046
25%,30209.500000,633.430500,210.804077,182.570992,1.135055,0.473031,30662.000000,196.122103,0.767216
50%,30834.000000,638.558000,212.826130,184.057998,1.158477,0.504781,31120.000000,198.139012,0.773098
75%,31158.000000,640.935000,214.104319,186.140285,1.176361,0.526603,31483.000000,199.177302,0.781997
max,31272.000000,670.033000,217.227813,187.535939,1.209713,0.562727,31593.000000,199.541342,0.798759

In [ ]:
data.head()

,Area,Perimeter,MajorAxisLength,MinorAxisLength,AspectRation,Eccentricity,ConvexArea,EquivDiameter,Extent
0,28395,610.291,208.178117,173.888747,1.197191,0.549812,28715,190.141097,0.763923
1,28734,638.018,200.524796,182.734419,1.097356,0.411785,29172,191.272751,0.783968
2,29380,624.110,212.826130,175.931143,1.209713,0.562727,29690,193.410904,0.778113
3,30008,645.884,210.557999,182.516516,1.153638,0.498616,30724,195.467062,0.782681
4,30140,620.134,201.847882,NaN,NaN,NaN,30417,195.896503,0.773098

In [ ]:
data.tail()

,Area,Perimeter,MajorAxisLength,MinorAxisLength,AspectRation,Eccentricity,ConvexArea,EquivDiameter,Extent
14,31158,641.105,212.066975,187.192960,1.132879,0.469924,31474,199.177302,0.781313
15,31178,636.888,212.975925,186.562088,1.141582,0.482352,31520,199.241217,0.764110
16,31202,644.454,215.640695,184.471684,1.168964,0.517871,31573,199.317888,0.779193
17,31203,639.782,215.067737,184.874876,1.163315,0.510947,31558,199.321081,0.762984
18,31272,638.666,212.450319,187.535939,1.132851,0.469883,31593,199.541342,0.770322

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Area             19 non-null     int64
 1   Perimeter        19 non-null     float64
 2   MajorAxisLength  19 non-null     float64
 3   MinorAxisLength  10 non-null     float64
 4   AspectRation     10 non-null     float64
 5   Eccentricity     10 non-null     float64
 6   ConvexArea       19 non-null     int64
 7   EquivDiameter    19 non-null     float64
 8   Extent           19 non-null     float64
dtypes: float64(7), int64(2)
memory usage: 1.5 KB

In [ ]:
data.isnull()

,Area,Perimeter,MajorAxisLength,MinorAxisLength,AspectRation,Eccentricity,ConvexArea,EquivDiameter,Extent
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,True,True,True,False,False,False
5,False,False,False,True,True,True,False,False,False
6,False,False,False,True,True,True,False,False,False
7,False,False,False,True,True,True,False,False,False
8,False,False,False,True,True,True,False,False,False
9,False,False,False,True,True,True,False,False,False
10,False,False,False,True,True,True,False,False,False
11,False,False,False,True,True,True,False,False,False
12,False,False,False,True,True,True,False,False,False
13,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False

In [ ]:
data.dropna(axis=1,inplace=True)
data

     Area  Perimeter  MajorAxisLength  ConvexArea  EquivDiameter    Extent
0   28395    610.291       208.178117       28715     190.141097  0.763923
1   28734    638.018       200.524796       29172     191.272751  0.783968
2   29380    624.110       212.826130       29690     193.410904  0.778113
3   30008    645.884       210.557999       30724     195.467062  0.782681
4   30140    620.134       201.847882       30417     195.896503  0.773098
5   30279    634.927       212.560556       30600     196.347702  0.775688
6   30477    670.033       211.050155       30970     196.988633  0.762402
7   30519    629.727       212.996755       30847     197.124320  0.770682
8   30685    635.681       213.534145       31044     197.659696  0.771561
9   30834    631.934       217.227813       31120     198.139012  0.783683
10  30917    640.765       213.560089       31280     198.405511  0.770805
11  31091    638.558       210.486255       31458     198.963039  0.786377
12  31107    640.594       214.648549       31423     199.014227  0.761046
13  31158    642.626       216.484836       31492     199.177302  0.798759
14  31158    641.105       212.066975       31474     199.177302  0.781313
15  31178    636.888       212.975925       31520     199.241217  0.764110
16  31202    644.454       215.640695       31573     199.317888  0.779193
17  31203    639.782       215.067737       31558     199.321081  0.762984
18  31272    638.666       212.450319       31593     199.541342  0.770322

In [ ]:
data.index

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18], dtype='int64')

In [ ]:
m=data.reindex([2,5,13,16,7])
m

,Area,Perimeter,MajorAxisLength,MinorAxisLength,AspectRation,Eccentricity,ConvexArea,EquivDiameter,Extent
2,29380,624.110,212.826130,175.931143,1.209713,0.562727,29690,193.410904,0.778113
5,30279,634.927,212.560556,NaN,NaN,NaN,30600,196.347702,0.775688
13,31158,642.626,216.484836,183.644312,1.178827,0.529514,31492,199.177302,0.798759
16,31202,644.454,215.640695,184.471684,1.168964,0.517871,31573,199.317888,0.779193
7,30519,629.727,212.996755,NaN,NaN,NaN,30847,197.124320,0.770682

In [ ]:
f=m.sort_index()
f

,Area,Perimeter,MajorAxisLength,MinorAxisLength,AspectRation,Eccentricity,ConvexArea,EquivDiameter,Extent
0,28395,610.291,208.178117,173.888747,1.197191,0.549812,28715,190.141097,0.763923
1,28734,638.018,200.524796,182.734419,1.097356,0.411785,29172,191.272751,0.783968
2,29380,624.110,212.826130,175.931143,1.209713,0.562727,29690,193.410904,0.778113
3,30008,645.884,210.557999,182.516516,1.153638,0.498616,30724,195.467062,0.782681
4,30140,620.134,201.847882,NaN,NaN,NaN,30417,195.896503,0.773098
5,30279,634.927,212.560556,NaN,NaN,NaN,30600,196.347702,0.775688
6,30477,670.033,211.050155,NaN,NaN,NaN,30970,196.988633,0.762402
7,30519,629.727,212.996755,NaN,NaN,NaN,30847,197.124320,0.770682
8,30685,635.681,213.534145,NaN,NaN,NaN,31044,197.659696,0.771561
9,30834,631.934,217.227813,NaN,NaN,NaN,31120,198.139012,0.783683
10,30917,640.765,213.560089,NaN,NaN,NaN,31280,198.405511,0.770805
11,31091,638.558,210.486255,NaN,NaN,NaN,31458,198.963039,0.786377
12,31107,640.594,214.648549,NaN,NaN,NaN,31423,199.014227,0.761046
13,31158,642.626,216.484836,183.644312,1.178827,0.529514,31492,199.177302,0.798759
14,31158,641.105,212.066975,187.192960,1.132879,0.469924,31474,199.177302,0.781313
15,31178,636.888,212.975925,186.562088,1.141582,0.482352,31520,199.241217,0.764110
16,31202,644.454,215.640695,184.471684,1.168964,0.517871,31573,199.317888,0.779193
17,31203,639.782,215.067737,184.874876,1.163315,0.510947,31558,199.321081,0.762984
18,31272,638.666,212.450319,187.535939,1.132851,0.469883,31593,199.541342,0.770322

In [ ]:
df.dropna(0,inplace=True)
df

<ipython-input-206-15fabf6f200e>:1: FutureWarning: In a future version of pandas all arguments of DataFrame.dropna will be keyword-only.
  df.dropna(0,inplace=True)

,Area,Perimeter,MajorAxisLength,MinorAxisLength,AspectRation,Eccentricity,ConvexArea,EquivDiameter,Extent
0,28395,610.291,208.178117,173.888747,1.197191,0.549812,28715,190.141097,0.763923
1,28734,638.018,200.524796,182.734419,1.097356,0.411785,29172,191.272751,0.783968
2,29380,624.110,212.826130,175.931143,1.209713,0.562727,29690,193.410904,0.778113
3,30008,645.884,210.557999,182.516516,1.153638,0.498616,30724,195.467062,0.782681
13,31158,642.626,216.484836,183.644312,1.178827,0.529514,31492,199.177302,0.798759
14,31158,641.105,212.066975,187.192960,1.132879,0.469924,31474,199.177302,0.781313
15,31178,636.888,212.975925,186.562088,1.141582,0.482352,31520,199.241217,0.764110
16,31202,644.454,215.640695,184.471684,1.168964,0.517871,31573,199.317888,0.779193
17,31203,639.782,215.067737,184.874876,1.163315,0.510947,31558,199.321081,0.762984
18,31272,638.666,212.450319,187.535939,1.132851,0.469883,31593,199.541342,0.770322

In [ ]:
df.shape

(10, 9)

In [ ]:
s=df.duplicated(subset=["Area"])
s

0     False
1     False
2     False
3     False
13    False
14     True
15    False
16    False
17    False
18    False
dtype: bool

In [ ]:
i=df.duplicated(subset=["Area","EquivDiameter"])
i

0     False
1     False
2     False
3     False
13    False
14     True
15    False
16    False
17    False
18    False
dtype: bool

In [ ]:
p=df.drop_duplicates(subset=["Area","EquivDiameter"])
p

,Area,Perimeter,MajorAxisLength,MinorAxisLength,AspectRation,Eccentricity,ConvexArea,EquivDiameter,Extent
0,28395,610.291,208.178117,173.888747,1.197191,0.549812,28715,190.141097,0.763923
1,28734,638.018,200.524796,182.734419,1.097356,0.411785,29172,191.272751,0.783968
2,29380,624.110,212.826130,175.931143,1.209713,0.562727,29690,193.410904,0.778113
3,30008,645.884,210.557999,182.516516,1.153638,0.498616,30724,195.467062,0.782681
13,31158,642.626,216.484836,183.644312,1.178827,0.529514,31492,199.177302,0.798759
15,31178,636.888,212.975925,186.562088,1.141582,0.482352,31520,199.241217,0.764110
16,31202,644.454,215.640695,184.471684,1.168964,0.517871,31573,199.317888,0.779193
17,31203,639.782,215.067737,184.874876,1.163315,0.510947,31558,199.321081,0.762984
18,31272,638.666,212.450319,187.535939,1.132851,0.469883,31593,199.541342,0.770322

In [ ]:
p.shape

(9, 9)

In [ ]:
df.describe()

,Area,Perimeter,MajorAxisLength,MinorAxisLength,AspectRation,Eccentricity,ConvexArea,EquivDiameter,Extent
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,30368.800000,636.182400,211.677353,182.935268,1.157632,0.500343,30751.100000,196.606795,0.776537
std,1144.198875,10.890324,4.618166,4.596936,0.033368,0.044262,1128.620343,3.730566,0.011328
min,28395.000000,610.291000,200.524796,173.888747,1.097356,0.411785,28715.000000,190.141097,0.762984
25%,29537.000000,637.170500,210.935243,182.570992,1.135055,0.473031,29948.500000,193.924944,0.765663
50%,31158.000000,639.224000,212.638224,184.057998,1.158477,0.504781,31483.000000,199.177302,0.778653
75%,31196.000000,642.245750,214.544784,186.140285,1.176361,0.526603,31548.500000,199.298720,0.782339
max,31272.000000,645.884000,216.484836,187.535939,1.209713,0.562727,31593.000000,199.541342,0.798759